@baseOrder=http://localhost:3000
@baseAuth=http://localhost:3001/auth

### CREATE ORDER
POST {{baseOrder}}/orders
Content-Type: application/json

{
  "name": "Snikers",
  "price": 24.00,
  "phoneNumber": "+123456789"
}

### GET all Orders
GET {{baseOrder}}/orders

### Create a new user
POST {{baseAuth}}/users
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testtest"
}

# {
#   "_id": "62e53033564f96182f9cd0e9",
#   "email": "test@gmail.com",
#   "password": "$2b$10$bZVxb12ad89k5cSwOIBdl.GyDWDKhbBHJBVggqPJIpjfcRfMP9bqq"
# }

### Login a user

POST {{baseAuth}}/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testtest"
}